### ISSUE TITLE
Syntax interfering with laravel

### ISSUE THREAD

**Issue by manjii** [jawee/language-blade#30]
I have both language-blade and atom-laravel packages installed. Your "section" trigger is outputting outdated @endsection directive, while it blocks the @stop directive from atom-laravel package.

**Comment by Ingramz** [comment]
atom-laravel snippets won't collide with ones provided here because they use a different grammar scope. But if you know how to fix this, send a pull request and I'll merge it and release asap or you'll have to wait till I'm back home from work.

**Comment by manjii** [comment]
I've edited language-blade.cson and it works just fine. 
Maybe it's not a proper place to ask about atom-laravel, but since you've already responded... I can't see atom-laravel's scope to select in atom editor. Do you know where can I toggle it?

**Comment by Ingramz** [comment]
Snippet scopes are very much dependent on the one in the grammar file. There is no magical way of changing this the way you like - you just have to change the hardcoded value. Instead of expecting some other package to provide that functionality for you, I'd strongly encourage you to update blade snippets right here in a form of pull request.

**Comment by manjii** [comment]
I'm still kinda new to all that programming stuff, so I don't really understand what do you mean by "pull request". I would be grateful if you could explain it to me, please.
