### ISSUE TITLE
@lang breaks inside javascript string.

### ISSUE THREAD

**Issue by bcalik** [jawee/language-blade#33]
See the screenshot below:

<img width="674" alt="screen shot 2016-01-15 at 21 05 07" src="https://cloud.githubusercontent.com/assets/9222368/12362453/13beb9f0-bbcc-11e5-99ed-c6ca0db49752.png">

**Comment by Ingramz** [comment]
Thank you for the bug report.

The reason for this happening is very simple. This grammar has been written to be greedy (blade consumes all `)` characters in order to attempt balancing opening brackets.

If we stop at the first `)`, then we might end too early - consider `@if(isset($condition) && somefunc($condition2))` - if we stop highlighting too early (we can pretty much stop only at the first `)`), the end won't be highlighted, this is why I opted to consume all parentheses instead.

Unfortunately I am not aware of a good solution here, suggestions based on other similar languages welcome.

As a workaround, you can style javascript so that the `'@lang("strings.continue")'` string is on its own line. This will make the grammar matching end before the javascript string is ended. Like so:

```js
somefun(
    '@lang("strings.continue")'
);
```

**Comment by bcalik** [comment]
Thanks for the workaround!

**Comment by Ingramz** [comment]
This issue should resolve itself when `atom/language-php` grammar gets matching parentheses support. Fingers crossed.

**Comment by Ingramz** [comment]
@bcalik This is long overdue, but I just released v0.31.0, please verify whether the issues you were having have now been solved.

**Comment by Ingramz** [comment]
Closing due to lack of feedback and inability to reproduce with newer version, assuming fixed.
