### ISSUE TITLE
Wrong colors if blade code is in html class

### ISSUE THREAD

**Issue by CalvinGrain** [jawee/language-blade#41]
![2016-05-02_1350](https://cloud.githubusercontent.com/assets/2598703/14952937/9f9f6870-106d-11e6-85b0-a278a1dc96b0.png)

Not a mayor issue, but worth mentioning.

**Comment by Ingramz** [comment]
Related to #33 - currently the underlying PHP grammar (atom/language-php) doesn't match parentheses. Because of that we don't know for sure if the first `)` character we encounter closes some function call from the condition or is meant to end a blade directive.

Currently the blade grammar is matching everything till the very last `)` on the line, which makes everything between colored like it was between `<?php ?>` tags.

The workaround is also similar to #33 - break the expression down to multiple lines.

**Comment by Ingramz** [comment]
@CalvinGrain I just released v0.31.0, please verify whether the issues you were having have now been solved.

**Comment by CalvinGrain** [comment]
It works perfect. Thank you!
