### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jbrooksuk** [jawee/language-blade#42]
What is the license for this project?

**Comment by Alhadis** [comment]
I was about to file this issue myself, haha.

@jawee The OP's asking because I've [recommended](https://github.com/github/linguist/pull/3008) this package be used to provide syntax highlighting for `.blade` files on GitHub. However, we can't use the grammar unless we know it's released under a permissive license (such as MIT or ISC).

Would you consider specifying a license?

Also, you misspelt "templating" in the repository's description. I tried holding myself back from pointing out the typo, but it was too tempting:

<img src="https://cloud.githubusercontent.com/assets/2346707/15363625/af0f98a6-1d5c-11e6-8408-06c3dbb27aa7.png" width="275" alt="topkek" />

**Comment by jawee** [comment]
I have honestly not thought about it. For me who does not know anything regarding licenses, I feel that people can do whatever they want with this. @Ingramz do you have any thoughts about this?

**Comment by Alhadis** [comment]
> I feel that people can do whatever they want with this.

That's exactly what the [ISC](http://choosealicense.com/licenses/isc/) license says in legal terms. =) I'd go with that.

**Comment by jawee** [comment]
I just want @Ingramz input as well, since he's the one who has done most work. :)

**Comment by Alhadis** [comment]
=) I'll greet him with something he doesn't expect an Australian to know.

Kõlab nagu perse kaudu hammaste ravimine. 😂😂😂👌

**Comment by Ingramz** [comment]
I am really flattered that this grammar is being suggested to Linguist.

Choosing a license has been in my backlog for a while, my vote would go for MIT, because this is what Atom uses - so why not to keep it uniform? While I have nothing against using ISC due to the end result being the same, I would go with MIT as it is more known of the two, but this is pretty much Coke vs Pepsi and I don't feel like drinking Pepsi.

@Alhadis this made me laugh (and think how painful the mentioned thing would be). But you were right, I didn't expect that.

**Comment by Alhadis** [comment]
MIT, ISC, either's fine. =)

Just steer clear of GPL or any other extremist copyleft nonsense, kuradi põrgu. :|

**Comment by Ingramz** [comment]
As for the typo mentioned in https://github.com/jawee/language-blade/issues/42#issuecomment-220053349, only @jawee can update it. It can be done straight from the repository page. While you are at it, change Laravel to uppercase, as it is a name.
