### ISSUE TITLE
TabLength gets overridden by php settings 

### ISSUE THREAD

**Issue by afilias-gtawaf** [jawee/language-blade#47]
I'm not able to leave  TabLength as 2 for language blade which is the default while php has a tabLength of 4.

I would like to have blade with tabLength as 2 and php as 4?

I'm using atom 1.8.0

Thanks

**Comment by Ingramz** [comment]
@afilias-gtawaf seems like you have found a bug, thank you for the report. I'll look into it immediately.

**Comment by Ingramz** [comment]
The issue seems to be with package `settings-view`. If you disable this package, you can manually set the config file to your desired values, as soon as you enable the package, it will reset it back to what it thinks are the "defaults" for blade.

I am going to try to fix this, but for time being there's no good solution other than disabling `settings-view`.

**Comment by Ingramz** [comment]
See also https://github.com/atom/settings-view/issues/774

**Comment by afilias-gtawaf** [comment]
Thanks  a lot it works now.

I reinstalled settings-view then set it to 2 and it seems to be working fine.

Thanks

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.12.0.

**Comment by Ingramz** [comment]
@50Wliu thanks for the heads up. :tada:

**Comment by kikoseijo** [comment]
This keeps working. 😩

**Comment by seleznevdev** [comment]
Same problem :disappointed:
