### ISSUE TITLE
How about including Laratrust?

### ISSUE THREAD

**Issue by rollercontainer** [jawee/language-blade#68]
Laratrust has some blade templates which might be worth including:

http://laratrust.readthedocs.io/en/3.2/usage/blade_templates.html

**Comment by Ingramz** [comment]
@rollercontainer thank you for the suggestion. Could you please explain in greater detail what are your expectations regarding what it should do or what do you mean by "including"?

**Comment by rollercontainer** [comment]
I suggest to include the keywords for syntax highlighting. See link above. (@permission, @endpermission etc)

**Comment by Ingramz** [comment]
Directive names that do not come with Blade by default are already highlighted, just differently. See the following example:

```blade
@if (true)
    <p>Useless statement</p>
@endif

@role('admin')
    <p>This is visible to users with the admin role. Gets translated to
    \Laratrust::hasRole('admin')</p>
@endrole

@permission('manage-admins')
    <p>This is visible to users with the given permissions. Gets translated to
    \Laratrust::can('manage-admins'). The @can directive is already taken by core
    laravel authorization package, hence the @permission directive instead.</p>
@endpermission

@ability('admin,owner', 'create-post,edit-user')
    <p>This is visible to users with the given abilities. Gets translated to
    \Laratrust::ability('admin,owner', 'create-post,edit-user')</p>
@endability

@canAndOwns('edit-post', $post)
    <p>This is visible if the user has the permission and owns the object. Gets translated to
    \Laratrust::canAndOwns('edit-post', $post)</p>
@endOwns

@hasRoleAndOwns('admin', $post)
    <p>This is visible if the user has the role and owns the object. Gets translated to
    \Laratrust::hasRoleAndOwns('admin', $post)</p>
@endOwns
```

**Comment by rollercontainer** [comment]
okay. Sorry, vote for close.

**Comment by Ingramz** [comment]
Closing by request.

However I will consider making this package more extendable via additional packages in the future. So that for instance if you are interested in Laratrust, you could make a package that can customize the look of its directives to look like the ones that come with Blade by default (or look different to what we have today), add additional snippets that are related to that package and perhaps even do auto-indent correctly for block-type directives. This way this package does not get too bloated or get maintenance-heavy regarding all the different projects that need to be tracked.
