### ISSUE TITLE
Inline "@yield" cause syntax highlight error

### ISSUE THREAD

**Issue by cytsunny** [jawee/language-blade#69]
![image](https://cloud.githubusercontent.com/assets/3927120/23789062/3aaaf53c-05b4-11e7-9115-b61db569e509.png)

The syntax is okay when separated into lines. However, when in oneline:

![image](https://cloud.githubusercontent.com/assets/3927120/23789121/6c822cba-05b4-11e7-9c06-5bcf28c9d7bb.png)

**Comment by Ingramz** [comment]
It has to do with greedy parenthesis matching that has been explained in https://github.com/jawee/language-blade/issues/33#issuecomment-172063712. All blade directives currently behave in a similar manner.

**Comment by Ingramz** [comment]
@cytsunny I just released v0.31.0, please verify whether the issues you were having have now been solved.

**Comment by cytsunny** [comment]
Yes, the problem is solved. Thanks for the update.

**Comment by cytsunny** [comment]
But I wonder how you solve the problem now? Isn't the problem caused by language-php package?

**Comment by Ingramz** [comment]
@cytsunny currently Blade grammar is a modified PHP grammar from language-php package and does not depend on you having a language-php package installed. This is due to an issue where PHP grammar cannot be currently included in other grammars, so we need to have a copy of it in the same file.

Every time I do commits like https://github.com/jawee/language-blade/commit/dca736cf8903c4739e7ace6662ddcd036883a781, I simply take what's available on language-php repository and just apply the changes here.

Of course following that commit on this repository are changes required to accommodate the changes from language-php, but these are rather trivial compared to what was done in the PHP grammar.
