### ISSUE TITLE
dosnt work Atom-Beautify

### ISSUE THREAD

**Issue by DonaldoLog** [jawee/language-blade#81]
![imagen](https://user-images.githubusercontent.com/24784827/36916852-b68478ac-1e1a-11e8-92f7-1a44c07234e7.png)
->

![imagen](https://user-images.githubusercontent.com/24784827/36916831-a788bca0-1e1a-11e8-876f-625f82913bf7.png)

but if we set HTML instead of BLADE, Atom-Beautify works.
![imagen](https://user-images.githubusercontent.com/24784827/36916914-f02c96c0-1e1a-11e8-86ce-95bf32702d05.png)

**Comment by Ingramz** [comment]
Thank you for the request. Unfortunately the support for beautifier needs to be added to atom-beautify package itself.

Please take a look at the [existing issues](https://github.com/Glavin001/atom-beautify/search?q=blade&type=Issues&utf8=%E2%9C%93) in atom-beautify repository. There is also a pull request that did not go through due to inactivity. If you are interested in adding the necessary support, you might want to take a look at it.

I am going to close this issue because it should belong to the atom-beautifier package, but feel free to ask any follow-up questions here if necessary.
