### ISSUE TITLE
This package collides with beautify

### ISSUE THREAD

**Issue by iwasherefirst2** [jawee/language-blade#89]
Note: I have also created an issue at js-beautify [here](https://github.com/beautify-web/js-beautify/issues/1725).

# Input
The code looked like this before beautification:
```
<script type="text/javascript">
     document.write( "@" );
</script>
```

# Expected Output
The code should have looked like this after beautification:
```
<script type="text/javascript">
     document.write( "@" );
</script>
```

# Actual Output
The  code actually looked like this after beautification:
```
<script type="text/javascript">
    document.write("<blade " / > );
</script>
```
# Steps to Reproduce
- Use ATOM editor
- Install package [atom-beautify](https://atom.io/packages/atom-beautify)
- create file with above content
- save as `test.blade.php` 
- run beautify

## Environment
OS: Ubuntu 18.04
Using Beautify in Atom Editor

Here is also a screencast showing the issue: https://www.youtube.com/watch?v=nyxBExWmEfo

**Comment by Ingramz** [comment]
How can I reproduce this, which Atom packages do need to be installed besides language-blade?

Assume that I know nothing about js-beautify.

**Comment by iwasherefirst2** [comment]
@Ingramz sry, I have updated my answer, including detailed steps to reproduce the issue aswell as a screencast

**Comment by Ingramz** [comment]
I took a look and when you have language-blade disabled, it will still do that when you run the `atom-beautify:beautify-language-blade` command manually (<kbd>ctrl/cmd</kbd> + <kbd>shift</kbd> + <kbd>p</kbd>, then paste it in).

If you try to just beautify without language-blade installed, then it will work in PHP mode, not Blade, that's why you noticed it only when you have language-blade installed.

**Comment by iwasherefirst2** [comment]
Your right! Sorry that I didn't check it by myself. Thank you for your quick reply.
